In [1]:
import numpy as np
v = np.array([3, 4])
print("Vector:", v)

Vector: [3 4]


In [2]:
vector = np.array([7,11,56,89])

In [4]:
print(vector)

[ 7 11 56 89]


In [5]:
vector=[
     [7,11,56,89],
     [7,11],
     [7,9],
     [7,11,56,8,9],
     [1],
]

In [22]:
vector=[
     [7,11],
     [7,10],
     [7,8],
     [7,1],
     [1,8],
]

In [23]:
print(vector)

[[7, 11], [7, 10], [7, 8], [7, 1], [1, 8]]


In [24]:
print("Length of outer list:", len(vector))
print("Lengths of each sub-list:", [len(sublist) for sublist in vector])

Length of outer list: 5
Lengths of each sub-list: [2, 2, 2, 2, 2]


In [25]:
arr = np.array(vector, dtype=object)
print("Array shape:", arr.shape)
print("Array data type:", arr.dtype)

Array shape: (5, 2)
Array data type: object


In [26]:
shape_of_vector=np.shape(vector)
print(shape_of_vector)

(5, 2)


Vector Addition & Multiplication

In [35]:
# a = np.array([1,2,5])
# b = np.array([3,4])
a = np.array([1,2])
b = np.array([3,4])
print(type(b))

<class 'numpy.ndarray'>


In [36]:
sum = a+b
print(sum)

[4 6]


In [38]:
a = np.array([1,2,5])
b = np.array([3])
scaled_vector = 3*a
print(scaled_vector)

[ 3  6 15]


6.Dot product Between vectors theory:
Dot Product = how similar two directions are.

In [41]:
a = np.array([1,2,5])
b = np.array([3,4,6])

In [42]:
dot = np.dot(a,b)
print("Dot Production:"), dot

Dot Production:


(None, np.int64(41))

In [43]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [1, 2],
    [3, 4]
])
result = np.dot(A,B)
print(result)

[[ 7 10]
 [15 22]]


In [1]:
import numpy as np

# Vector of 3 elements
v = np.array([1, 2, 3])
print("Vector v:", v)
print("Shape:", v.shape)  # Output: (3,)


Vector v: [1 2 3]
Shape: (3,)


In [2]:
# Matrix of 2 rows and 3 columns
M = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix M:\n", M)
print("Shape:", M.shape)  # Output: (2, 3)


Matrix M:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


2: Fixing Vector-Matrix Shape Errors – With Code and Explanations
Shape mismatch errors happen when dimensions don’t align for operations like matrix multiplication or broadcasting.

In [3]:
v = np.array([1, 2, 3])
M = np.array([[1, 2], [3, 4]])  # Shape (2,2)

# This will throw an error: incompatible shapes for dot product
result = np.dot(v, M)  # ValueError!


ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

Fix: Reshape the vector properly

In [4]:
v = np.array([1, 2])
M = np.array([[1, 2], [3, 4]])

# Now shapes match: (1,2) x (2,2) -> (1,2)
v_reshaped = v.reshape(1, 2)
result = np.dot(v_reshaped, M)
print("Result:\n", result)


Result:
 [[ 7 10]]


3: Vector-Matrix Operations in AI – With Code and Explanations
These operations are crucial in AI, especially in neural networks, linear regression, and embeddings.

➤ Dot Product (Neural Layers)

In [5]:
# Input vector and weight matrix
x = np.array([0.5, 1.5])               # Shape: (2,)
W = np.array([[0.1, 0.3], [0.2, 0.4]]) # Shape: (2,2)

# Output = x · W
output = np.dot(x, W)
print("Output:", output)  # Shape: (2,)


Output: [0.35 0.75]


Broadcasting (Bias Addition)

In [6]:
bias = np.array([0.1, 0.2])
activated = output + bias  # Adds element-wise (shape match)
print("Activated Output:", activated)


Activated Output: [0.45 0.95]


4: Shape Mismatch Fixes in AI – With Code and Explanations
🔻 Common AI Scenario: Input × Weights + Bias

In [7]:
# Batch of 2 samples, each with 3 features
X = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)

# Weight matrix for 3 inputs to 2 outputs
W = np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])  # Shape: (3, 2)

# Bias vector
b = np.array([0.1, 0.2])  # Shape: (2,)

# Correct shape: (2,3) x (3,2) + (2,) => (2,2)
Z = np.dot(X, W) + b
print("Output Z:\n", Z)


Output Z:
 [[2.3 3. ]
 [5.  6.6]]


In [8]:
#Common Error: Incorrect bias shape
# Wrong shape
b_wrong = np.array([[0.1], [0.2]])  # Shape: (2,1)

# This may throw a broadcasting error
Z = np.dot(X, W) + b_wrong  # ❌


Fix: Ensure shapes are aligned or use .reshape() or .broadcast_to()

In [9]:
b_fixed = b.reshape(1, 2)  # Shape (1,2) broadcastable with (2,2)
Z = np.dot(X, W) + b_fixed  # ✅
